package com.example.realestatesearchapp;

public class Location_values {
	private static String[] cities = { "Abba", "Abbeville", "Acworth",
			"Adairsville", "Adel", "Adrian", "Ailey", "Alamo", "Alapaha",
			"Albany", "Allenhurst", "Alma", "Alma", "Alpharetta", "Alston",
			"Amboy", "Ambrose", "Americus", "Appling", "Arlington", "Ashburn",
			"Athens", "Atkinson", "Atlanta", "Attapulgus", "Auburn", "Augusta",
			"Augusta-Richmond County", "Austell", "Avondale Estates", "Axson",
			"Baconton", "Baden", "Bainbridge", "Bainbridge", "Baldwin",
			"Bannockburn", "Barnesville", "Barney", "Barretts", "Barwick",
			"Baxley", "Bemiss", "Berkeley Lake", "Berlin", "Blackshear",
			"Blairsville", "Blakely", "Bloomingdale", "Blue Ridge", "Bogart",
			"Boston", "Bowdon", "Bowens Mill", "Bowman", "Braselton", "Bremen",
			"Brinson", "Bristol", "Bronwood", "Brookfield", "Brooklet",
			"Brooks", "Broxton", "Brunswick", "Buchanan", "Buena Vista",
			"Buford", "Bushnell", "Byromville", "Byron", "Cairo", "Camilla",
			"Canton", "Carnesville", "Carrollton", "Cartersville",
			"Cave Spring", "Cecil", "Cedartown", "Centerville", "Chamblee",
			"Chatsworth", "Chauncey", "Chester", "Chickamauga", "Chula",
			"Clarkston", "Claxton", "Clayton", "Cleveland", "Clyatteville",
			"Clyo", "Cobbtown", "Cochran", "Cogdell", "Cohutta", "Colesburg",
			"College Park", "Collins", "Colquitt", "Columbus", "Commerce",
			"Conyers", "Coolidge", "Cordele", "Cornelia", "Council",
			"Country Club Estate", "Coverdale", "Covington", "Cox",
			"Crawfordville", "Crescent", "Culloden", "Cumming", "Cusseta",
			"Cuthbert", "Dacula", "Dahlonega", "Daisy", "Dakota", "Dallas",
			"Dalton", "Damascus", "Danielsville", "Darien", "Dasher", "Dawson",
			"Dawsonville", "Decatur", "Denmark", "Dillard", "Dixie",
			"Dock Junction", "Doerun", "Donalsonville", "Doraville", "Douglas",
			"Douglasville", "Dover Bluff", "Dupont", "Dublin", "Dudley",
			"Duluth", "Dunwoody", "East Dublin", "East Point", "Eastman",
			"Eatonton", "Ebenezer", "Edison", "Edith", "Egypt", "Elberton",
			"Eldorado", "Ellabelle", "Ellaville", "Ellenton", "Ellijay",
			"Enigma", "Euharlee", "Eulonia", "Everitt", "Fairburn", "Fairmont",
			"Fargo", "Fayetteville", "Fitzgerald", "Flemington",
			"Flowery Branch", "Folkston", "Forest Park", "Forsyth",
			"Fort Gaines", "Fort Oglethorpe", "Fort Stewart", "Fort Valley",
			"Franklin", "Fruitland", "Funston", "Gainesville", "Garden City",
			"Garfield", "Geneva", "Georgetown", "Gibson", "Glennville",
			"Glenwood", "Glory", "Graham", "Gray", "Greensboro", "Greenville",
			"Griffin", "Grooverville", "Groveland", "Grovetown", "Gumbranch",
			"Guyton", "Hagan", "Hahira", "Hamilton", "Hampton", "Hapeville",
			"Harding", "Harding", "Hardwicke", "Harrietts Bluff", "Hartwell",
			"Hawkinsville", "Haylon", "Hazlehurst", "Helena", "Hepzibah",
			"Hiawassee", "Hickox", "Higgston", "Hinesville", "Hiram",
			"Hoboken", "Hogansville", "Holly Springs", "Holt", "Homeland",
			"Homer", "Homerville", "Hopeulikit", "Hortense", "Howell", "Inaha",
			"Iron City", "Irwinton", "Irwinville", "Isle Of Hope-Dutch Island",
			"Jackson", "Janis", "Jasper", "Jefferson", "Jeffersonville",
			"Jesup", "Johns Creek", "Jonesboro", "Keller", "Kennesaw",
			"Kinderlou", "Kings Bay Base", "Kingsland", "Kirkland", "Kite",
			"Lafayette", "Lagrange", "Lake City", "Lake Park", "Lakeland",
			"Lanier", "Lawrenceville", "Lax", "Leary", "Leefield", "Leesburg",
			"Lenox", "Lexington", "Lilburn", "Lincolnton", "Lithonia",
			"Locust Grove", "Loganville", "Lookout Mountain", "Louisville",
			"Lovejoy", "Ludowici", "Lulaton", "Lumber City", "Lumpkin",
			"Lyons", "Macon", "Madison", "Manassas", "Manchester", "Marietta",
			"Maxeys", "Mayday", "Mcdonough", "Mcintosh", "Mcintyre", "Mcrae",
			"Meigs", "Meldrim", "Mershon", "Metter", "Midway", "Milan",
			"Milledgeville", "Millen", "Milton", "Moniac", "Monroe",
			"Montezuma", "Montgomery", "Monticello", "Montrose", "Mora",
			"Morgan", "Morrow", "Morven", "Moultrie", "Mount Vernon",
			"Mount Zion", "Mountain Park", "Mystic", "Nahunta", "Nankin",
			"Nashville", "Needmore", "Nelson", "Nevils", "New Rock Hill",
			"Newnan", "Newton", "Nicholls", "Norcross", "Norman Park",
			"Oakwood", "Ochlocknee", "Ocilla", "Odum", "Offerman", "Offerman",
			"Oglethorpe", "Omega", "Osterfield", "Ousley", "Oxford",
			"Palmetto", "Parrott", "Patterson", "Peachtree City Website",
			"Pearson", "Pelham", "Pembroke", "Perry", "Phillipsburg",
			"Pine Lake", "Pineora", "Pineview", "Pooler", "Port Wentworth",
			"Portal", "Potter", "Poulan", "Powder Springs", "Preston",
			"Pridgen", "Pulaski", "Queensland", "Quitman", "Ray City",
			"Rebecca", "Register", "Reidsville", "Remerton", "Rentz",
			"Retreat", "Riceboro", "Richmond Hill", "Ridgeville", "Rincon",
			"Ringgold", "Riverdale", "Riverside", "Rochelle", "Rockingham",
			"Rockmart", "Rome", "Roswell", "Royston", "Rutledge",
			"Saint George", "Sale City", "Sandersville", "Sandy Springs",
			"Sasser", "Savannah", "Screven", "Senoia", "Sessoms", "Shawnee",
			"Shellman Bluff", "Sirmans", "Skidaway Island", "Smithville",
			"Smyrna", "Snellville", "Social Circle", "Soperton",
			"South Newport", "Sparks", "Sparta", "Springfield", "Strongsville",
			"St. Simons Island", "Statenville", "Statesboro", "Sterling",
			"Stillmore", "Stillwell", "Stilson", "Stockbridge", "Stockton",
			"Stone Mountain", "Sugar Hill", "Sumner", "Sunbury", "Sunsweet",
			"Surrency", "Suwanee", "Swainsboro", "Sycamore", "Sylvania",
			"Sylvester", "Talbotton", "Tallapoosa", "Tarboro", "Tarver",
			"Temple", "Thalman", "Thelma", "Thomaston", "Thomasville",
			"Thomson", "Thunderbolt", "Tifton", "Toccoa", "Toomsboro",
			"Townsend", "Trenton", "Trudie", "Tucker", "Twin City",
			"Twin Peaks", "Tybee Island", "Tyrone", "Unadilla", "Union City",
			"Unionville", "Upton", "Uvalda", "Valdosta", "Valona",
			"Vernonburg", "Vidalia", "Vienna", "Villa Rica", "Walthourville",
			"Warrenton", "Warwick", "Washington", "Waterloo", "Watkinsville",
			"Waverly", "Waycross", "Waynesboro", "Waynesville", "Weber",
			"West Green", "West Point", "Westwood", "Whigham", "White Oak",
			"Whitmarsh Island", "Willacoochee", "Wilmington Island", "Winder",
			"Winokur", "Withers", "Woodbine", "Woodstock", "Worth", "Wray",
			"Wrightsville" };
	public static String[] getCities() {
		return cities;
	}
	
}
